# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20191104_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.Author', verbose_name='相公')),
            ],
        ),
    ]
