# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_wife'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wife',
            options={'verbose_name': '夫人', 'verbose_name_plural': '夫人'},
        ),
        migrations.AlterModelTable(
            name='wife',
            table='wife',
        ),
    ]
